<template><div><h1 id="data-自定义属性" tabindex="-1"><a class="header-anchor" href="#data-自定义属性" aria-hidden="true">#</a> <a href="https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/data-*" target="_blank" rel="noopener noreferrer">data-*自定义属性<ExternalLinkIcon/></a></h1>
<h2 id="自定义属性" tabindex="-1"><a class="header-anchor" href="#自定义属性" aria-hidden="true">#</a> 自定义属性</h2>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>ul<span class="token operator">></span>
    <span class="token operator">&lt;</span>li data<span class="token operator">-</span>id<span class="token operator">=</span><span class="token string">"10784"</span><span class="token operator">></span>Jason Walters<span class="token punctuation">,</span> <span class="token number">003</span><span class="token operator">:</span> Found dead <span class="token keyword">in</span> <span class="token string">"A View to a Kill"</span><span class="token punctuation">.</span><span class="token operator">&lt;</span><span class="token operator">/</span>li<span class="token operator">></span>
    <span class="token operator">&lt;</span>li data<span class="token operator">-</span>id<span class="token operator">=</span><span class="token string">"97865"</span><span class="token operator">></span>Alex Trevelyan<span class="token punctuation">,</span> <span class="token number">006</span><span class="token operator">:</span> Agent turned terrorist leader<span class="token punctuation">;</span> James' nemesis <span class="token keyword">in</span> <span class="token string">"Goldeneye"</span><span class="token punctuation">.</span><span class="token operator">&lt;</span><span class="token operator">/</span>li<span class="token operator">></span>
    <span class="token operator">&lt;</span>li data<span class="token operator">-</span>id<span class="token operator">=</span><span class="token string">"45732"</span><span class="token operator">></span>James Bond<span class="token punctuation">,</span> <span class="token number">007</span><span class="token operator">:</span> The main man<span class="token punctuation">;</span> shaken but not stirred<span class="token punctuation">.</span><span class="token operator">&lt;</span><span class="token operator">/</span>li<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>ul<span class="token operator">></span>
</code></pre></div><p>所有这些自定义数据属性都可以通过所属元素的 <a href="https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement" target="_blank" rel="noopener noreferrer"><code v-pre>HTMLElement</code><ExternalLinkIcon/></a> 接口来访问。 <a href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset" target="_blank" rel="noopener noreferrer"><code v-pre>HTMLElement.dataset</code> (en-US)<ExternalLinkIcon/></a> 属性可以访问它们。 <code v-pre>*</code> 可以使用遵循 <a href="https://www.w3.org/TR/REC-xml/#NT-Name" target="_blank" rel="noopener noreferrer">xml 名称生产规则<ExternalLinkIcon/></a> 的任何名称来被替换，并具有以下限制：</p>
<ol>
<li>该名称不能以<code v-pre>xml</code>开头，无论这些字母是大写还是小写；</li>
<li>该名称不能包含任何分号 (<code v-pre>U+003A</code>)；</li>
<li>该名称不能包含 A 至 Z 的大写字母。</li>
</ol>
<p>注意，<a href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset" target="_blank" rel="noopener noreferrer"><code v-pre>HTMLElement.dataset</code> (en-US)<ExternalLinkIcon/></a> 属性是一个<a href="https://developer.mozilla.org/zh-CN/docs/Web/API/DOMStringMap" target="_blank" rel="noopener noreferrer"><code v-pre>DOMStringMap</code><ExternalLinkIcon/></a></p>
<h2 id="使用数据属性" tabindex="-1"><a class="header-anchor" href="#使用数据属性" aria-hidden="true">#</a> 使用数据属性</h2>
<p><a href="https://developer.mozilla.org/en-US/docs/Glossary/HTML5" target="_blank" rel="noopener noreferrer">HTML5<ExternalLinkIcon/></a>是具有扩展性的设计，它初衷是数据应与特定的元素相关联，但不需要任何定义。<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#data-*" target="_blank" rel="noopener noreferrer">data-* 属性<ExternalLinkIcon/></a>允许我们在标准内于 HTML 元素中存储额外的信息，而不需要使用类似于 <a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/classList" target="_blank" rel="noopener noreferrer">classList<ExternalLinkIcon/></a>，</p>
<h2 id="javascript-访问" tabindex="-1"><a class="header-anchor" href="#javascript-访问" aria-hidden="true">#</a> JavaScript 访问</h2>
<p>在外部使用<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noopener noreferrer">JavaScript<ExternalLinkIcon/></a>去访问这些属性的值同样非常简单。你可以使用<a href="https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getAttribute" target="_blank" rel="noopener noreferrer"><code v-pre>getAttribute()</code><ExternalLinkIcon/></a>配合它们完整的 HTML 名称去读取它们，但标准定义了一个更简单的方法：<a href="https://developer.mozilla.org/zh-CN/docs/Web/API/DOMStringMap" target="_blank" rel="noopener noreferrer"><code v-pre>DOMStringMap</code><ExternalLinkIcon/></a>你可以使用<a href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset" target="_blank" rel="noopener noreferrer"><code v-pre>dataset</code> (en-US)<ExternalLinkIcon/></a>读取到数据。</p>
<p>为了使用<code v-pre>dataset</code>对象去获取到数据属性，需要获取属性名中<code v-pre>data-</code>之后的部分 (要注意的是破折号连接的名称需要改写为骆驼拼写法 (如&quot;index-number&quot;转换为&quot;indexNumber&quot;))。</p>
<div class="language-html ext-html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>article</span>
  <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>electriccars<span class="token punctuation">"</span></span>
  <span class="token attr-name">data-columns</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>3<span class="token punctuation">"</span></span>
  <span class="token attr-name">data-index-number</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>12314<span class="token punctuation">"</span></span>
  <span class="token attr-name">data-parent</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>cars<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
...
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>article</span><span class="token punctuation">></span></span>
</code></pre></div><div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> article <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'#electriccars'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

article<span class="token punctuation">.</span>dataset<span class="token punctuation">.</span>columns <span class="token comment">// "3"</span>
article<span class="token punctuation">.</span>dataset<span class="token punctuation">.</span>indexNumber <span class="token comment">// "12314"</span>
article<span class="token punctuation">.</span>dataset<span class="token punctuation">.</span>parent <span class="token comment">// "cars"</span>
</code></pre></div><h2 id="css访问" tabindex="-1"><a class="header-anchor" href="#css访问" aria-hidden="true">#</a> CSS访问</h2>
<p>注意，data 设定为 HTML 属性，他们同样能被<a href="https://developer.mozilla.org/en-US/docs/Web/CSS" target="_blank" rel="noopener noreferrer">CSS<ExternalLinkIcon/></a>访问。比如你可以通过<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/content" target="_blank" rel="noopener noreferrer">generated content<ExternalLinkIcon/></a>使用函数<a href="https://developer.mozilla.org/zh-CN/docs/Web/CSS/attr" target="_blank" rel="noopener noreferrer"><code v-pre>attr()</code><ExternalLinkIcon/></a>来显示 data-parent 的内容：</p>
<div class="language-css ext-css"><pre v-pre class="language-css"><code><span class="token selector">article::before</span> <span class="token punctuation">{</span>
  <span class="token property">content</span><span class="token punctuation">:</span> <span class="token function">attr</span><span class="token punctuation">(</span>data-parent<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>你也同样可以在 CSS 中使用<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors" target="_blank" rel="noopener noreferrer">属性选择器<ExternalLinkIcon/></a>根据 data 来改变样式：</p>
<div class="language-css ext-css"><pre v-pre class="language-css"><code><span class="token selector">article[data-columns='3']</span> <span class="token punctuation">{</span>
  <span class="token property">width</span><span class="token punctuation">:</span> 400px<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token selector">article[data-columns='4']</span> <span class="token punctuation">{</span>
  <span class="token property">width</span><span class="token punctuation">:</span> 600px<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>Data 属性同样可以存储不断变化的信息，比如游戏的得分。使用 CSS 选择器与 JavaScript 去访问可以让你得到花俏的效果，这里你并不需要用常规的编写方案来编写代码。有关使用生成内容和 CSS 转换（<a href="https://jsbin.com/atawaz/3/edit" target="_blank" rel="noopener noreferrer">JSBin 示例<ExternalLinkIcon/></a>）的示例，请参阅此<a href="https://www.youtube.com/watch?v=On_WyUB1gOk" target="_blank" rel="noopener noreferrer">视频<ExternalLinkIcon/></a>。</p>
<p>数据值是字符串。必须在选择器中引用数值才能使样式生效。</p>
</div></template>
