<template><div><h1 id="math对象在线文档-math-javascript-mdn-mozilla-org" tabindex="-1"><a class="header-anchor" href="#math对象在线文档-math-javascript-mdn-mozilla-org" aria-hidden="true">#</a> [Math对象在线文档](<a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Math" target="_blank" rel="noopener noreferrer">Math - JavaScript | MDN (mozilla.org)<ExternalLinkIcon/></a>)</h1>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>	<span class="token comment">// 随机点名</span>
    <span class="token keyword">let</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'赵云'</span><span class="token punctuation">,</span> <span class="token string">'黄忠'</span><span class="token punctuation">,</span> <span class="token string">'关羽'</span><span class="token punctuation">,</span> <span class="token string">'张飞'</span><span class="token punctuation">,</span> <span class="token string">'马超'</span><span class="token punctuation">,</span> <span class="token string">'刘备'</span><span class="token punctuation">,</span> <span class="token string">'曹操'</span><span class="token punctuation">]</span>
    <span class="token comment">// 1. 得到一个随机数， 作为数组的索引号， 这个随机数 0~6</span>
    <span class="token keyword">let</span> random <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">*</span> arr<span class="token punctuation">.</span>length<span class="token punctuation">)</span>
    <span class="token comment">// 2. 页面输出数组里面的元素 </span>
    document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>arr<span class="token punctuation">[</span>random<span class="token punctuation">]</span><span class="token punctuation">)</span>

    <span class="token comment">// 3. splice(起始位置(下标), 删除几个元素)</span>
    arr<span class="token punctuation">.</span><span class="token function">splice</span><span class="token punctuation">(</span>random<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>arr<span class="token punctuation">)</span>
</code></pre></div></div></template>
